Imported sqliteodbc-0.991.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SQLITE_INC SQLITE_LIB SQLITE_LIBVERSION SQLITE_ENCDEC SQLITE_ATOF SQLITE_MPRINTF SQLITE_TRACE SQLITE3_INC SQLITE3_A10N_C SQLITE3_A10N_O SQLITE3_A10N_FLAGS SQLITE3_COLUMNTABLENAME SQLITE3_OVERLOADFUNCTION SQLITE3_PREPARE_V2 SQLITE3_CLEARBINDINGS SQLITE3_CREATEMODULE_V2 SQLITE3_LOADEXTENSION SQLITE3_TABLECOLUMNMETADATA SQLITE3_VFS SQLITE3_PROFILE SQLITE3_STRNICMP EXT_BLOBTOXY EXT_IMPEXP EXT_CSVTABLE EXT_ZIPFILE LIB_TARGETS INST_TARGETS UNINST_TARGETS DRVINST_TARGETS DRVUNINST_TARGETS ODBC_FLAGS ODBC_LIB VER_INFO DRVDIR DL_OPTS DL_INITFINI SQLITE3_LIB SPEC_CHANGELOG_TS DEB_CHANGELOG_TS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT SED EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB STRIP ac_ct_STRIP CPP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SQLITE_INC SQLITE_LIB SQLITE_LIBVERSION SQLITE_ENCDEC SQLITE_ATOF SQLITE_MPRINTF SQLITE_TRACE SQLITE3_INC SQLITE3_A10N_C SQLITE3_A10N_FLAGS SQLITE3_COLUMNTABLENAME SQLITE3_OVERLOADFUNCTION SQLITE3_PREPARE_V2 SQLITE3_CLEARBINDINGS SQLITE3_CREATEMODULE_V2 SQLITE3_LOADEXTENSION SQLITE3_TABLECOLUMNMETADATA SQLITE3_VFS SQLITE3_PROFILE SQLITE3_STRNICMP EXT_BLOBTOXY EXT_IMPEXP EXT_CSVTABLE EXT_ZIPFILE SQLITE4_INC SQLITE4_A10N_C SQLITE4_A10N_FLAGS XML2_FLAGS XML2_LIBS EXT_XPATH LIB_TARGETS INST_TARGETS UNINST_TARGETS DRVINST_TARGETS DRVUNINST_TARGETS ODBC_FLAGS ODBC_LIB VER_INFO DRVDIR DL_OPTS DL_INITFINI SQLITE3_LIB SQLITE3_A10N_O SQLITE4_A10N_O SPEC_CHANGELOG_TS DEB_CHANGELOG_TS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1037,8 +1037,9 @@ Optional Packages:
                           include additional configurations [automatic]
   --with-sqlite=DIR       use SQLite header/lib from DIR
   --with-sqlite3=DIR      use SQLite3 hdr/lib from DIR
+  --with-sqlite4=DIR      use SQLite4 hdr/src from DIR
   --with-odbc=DIR         use ODBC header/libs from DIR
-  --with-dls              dlopen SQLite3 lib
+  --with-dls              dlopen SQLite3/SQLite4 lib
 
 Some influential environment variables:
   CC          C compiler command
@@ -3069,7 +3070,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3072 "configure"' > conftest.$ac_ext
+  echo '#line 3073 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4559,7 +4560,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4562:" \
+echo "$as_me:4563:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5626,11 +5627,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5629: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5630: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5633: \$? = $ac_status" >&5
+   echo "$as_me:5634: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -5894,11 +5895,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5897: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5898: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5901: \$? = $ac_status" >&5
+   echo "$as_me:5902: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -5998,11 +5999,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6001: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6002: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6005: \$? = $ac_status" >&5
+   echo "$as_me:6006: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7467,7 +7468,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 7470 "configure"' > conftest.$ac_ext
+    echo '#line 7471 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8364,7 +8365,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8367 "configure"
+#line 8368 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8464,7 +8465,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8467 "configure"
+#line 8468 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10811,11 +10812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10814: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10818: \$? = $ac_status" >&5
+   echo "$as_me:10819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10915,11 +10916,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10918: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10919: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10922: \$? = $ac_status" >&5
+   echo "$as_me:10923: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11451,7 +11452,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11454 "configure"' > conftest.$ac_ext
+    echo '#line 11455 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12509,11 +12510,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12512: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12513: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12516: \$? = $ac_status" >&5
+   echo "$as_me:12517: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12613,11 +12614,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12616: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12617: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12620: \$? = $ac_status" >&5
+   echo "$as_me:12621: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14062,7 +14063,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14065 "configure"' > conftest.$ac_ext
+    echo '#line 14066 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -14844,11 +14845,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14847: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14848: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14851: \$? = $ac_status" >&5
+   echo "$as_me:14852: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15112,11 +15113,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15115: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15116: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15119: \$? = $ac_status" >&5
+   echo "$as_me:15120: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15216,11 +15217,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15219: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15220: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15223: \$? = $ac_status" >&5
+   echo "$as_me:15224: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16685,7 +16686,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 16688 "configure"' > conftest.$ac_ext
+    echo '#line 16689 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18593,7 +18594,6 @@ fi
 
 
 
-
 # test for availability of some sqlite3_*() funcs
 
 if test -n "$SQLITE3_LIBDIR" ; then
@@ -18601,14 +18601,15 @@ if test -n "$SQLITE3_LIBDIR" ; then
 fi
 
 if test -n "$SQLITE3_A10N_C" ; then
-   SQLITE3_LOADEXTENSTION=1
+   SQLITE3_LOADEXTENSION=1
    SQLITE3_COLUMNTABLENAME=1
    SQLITE3_OVERLOADFUNCTION=1
    SQLITE3_PREPARE_V2=1
    SQLITE3_CLEARBINDINGS=1
    SQLITE3_CREATEMODULE_V2=1
-   SQLITE3_TABLECOLUMNMETADATA=1
    SQLITE3_VFS=1
+   SQLITE3_TABLECOLUMNMETADATA=1
+   SQLITE3_PROFILE=1
    SQLITE3_STRNICMP=1
 else
    saved_CFLAGS=$CFLAGS
@@ -19710,6 +19711,84 @@ fi
 
 
 
+
+
+
+
+##########
+# Find SQLite4 header file and library
+#
+
+# Check whether --with-sqlite4 or --without-sqlite4 was given.
+if test "${with_sqlite4+set}" = set; then
+  withval="$with_sqlite4"
+  SQLITE4_DIR=$withval
+fi;
+if test -n "$SQLITE4_DIR" ; then
+   if test ! -d "$SQLITE4_DIR" ; then
+      { echo "$as_me:$LINENO: WARNING: SQLite4 directory $SQLITE4_DIR does not exist" >&5
+echo "$as_me: WARNING: SQLite4 directory $SQLITE4_DIR does not exist" >&2;}
+   fi
+fi
+
+SQLITE4_INC=UNKNOWN
+
+if test -n "$SQLITE4_DIR" ; then
+   echo "$as_me:$LINENO: checking for SQLite4 header and library" >&5
+echo $ECHO_N "checking for SQLite4 header and library... $ECHO_C" >&6
+   for i in $SQLITE4_DIR ; do
+      if test -r "$i/sqlite4.h" ; then
+         if test -r "$i/sqlite4.c" ; then
+            SQLITE4_INC="$i"
+            SQLITE4_A10N_C="$i/sqlite4.c"
+            SQLITE4_A10N_O="sqlite4.lo"
+            break
+         fi
+      fi
+   done
+fi
+if test "$SQLITE4_INC" = "UNKNOWN" ; then
+   echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+   { echo "$as_me:$LINENO: WARNING: SQLite4 header file and source not found" >&5
+echo "$as_me: WARNING: SQLite4 header file and source not found" >&2;}
+else
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+   LIB_TARGETS="$LIB_TARGETS libsqlite4odbc.la"
+   INST_TARGETS="$INST_TARGETS install-4"
+   UNINST_TARGETS="$UNINST_TARGETS uninstall-4"
+   DRVINST_TARGETS="$DRVINST_TARGETS drvinst-4"
+   DRVUNINST_TARGETS="$DRVUNINST_TARGETS drvuninst-4"
+   SQLITE4_A10N_FLAGS="$SQLITE4_A10N_FLAGS -DSQLITE4_ENABLE_COLUMN_METADATA=1"
+   SQLITE4_A10N_FLAGS="$SQLITE4_A10N_FLAGS -DSQLITE4_SOUNDEX=1"
+   SQLITE4_A10N_FLAGS="$SQLITE4_A10N_FLAGS -DSQLITE4_THREADSAFE=1"
+fi
+
+
+
+
+#########
+# libxml2 support for XPath virtual table module
+XML2_FLAGS=""
+XML2_LIBS=""
+EXT_XPATH=""
+if test "$SQLITE3_LOADEXTENSION" = "1" ; then
+   echo "$as_me:$LINENO: checking for libxml2 header and library" >&5
+echo $ECHO_N "checking for libxml2 header and library... $ECHO_C" >&6
+   XML2_CONFIG="`which xml2-config 2>/dev/null`"
+   if test -n "$XML2_CONFIG" ; then
+      XML2_FLAGS="`xml2-config --cflags`"
+      XML2_LIBS="`xml2-config --libs`"
+      EXT_XPATH=libsqlite3_mod_xpath.la
+      LIB_TARGETS="$LIB_TARGETS $EXT_XPATH"
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+   else
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+   fi
+fi
 
 
 
@@ -21196,7 +21275,7 @@ fi
 
 
 ##########
-# Experimental: dlopen for resolving SQLite3 symbols
+# Experimental: dlopen for resolving SQLite3/SQLite4 symbols
 #
 
 # Check whether --with-dls or --without-dls was given.
@@ -21210,9 +21289,13 @@ if test "$DLOPENFORGPPS" = "1" ; then
    if test "$WITH_DLS" = "1" ; then
       DL_OPTS="-DSQLITE_DYNLOAD=1"
       SQLITE3_LIB=""
+      SQLITE3_A10N_O=""
+      SQLITE4_A10N_O=""
       DL_INITFINI="-Wl,-init,dls_init -Wl,-fini,dls_fini"
    fi
 fi
+
+
 
 
 
@@ -21908,7 +21991,6 @@ s,@SQLITE_MPRINTF@,$SQLITE_MPRINTF,;t t
 s,@SQLITE_TRACE@,$SQLITE_TRACE,;t t
 s,@SQLITE3_INC@,$SQLITE3_INC,;t t
 s,@SQLITE3_A10N_C@,$SQLITE3_A10N_C,;t t
-s,@SQLITE3_A10N_O@,$SQLITE3_A10N_O,;t t
 s,@SQLITE3_A10N_FLAGS@,$SQLITE3_A10N_FLAGS,;t t
 s,@SQLITE3_COLUMNTABLENAME@,$SQLITE3_COLUMNTABLENAME,;t t
 s,@SQLITE3_OVERLOADFUNCTION@,$SQLITE3_OVERLOADFUNCTION,;t t
@@ -21924,6 +22006,12 @@ s,@EXT_BLOBTOXY@,$EXT_BLOBTOXY,;t t
 s,@EXT_IMPEXP@,$EXT_IMPEXP,;t t
 s,@EXT_CSVTABLE@,$EXT_CSVTABLE,;t t
 s,@EXT_ZIPFILE@,$EXT_ZIPFILE,;t t
+s,@SQLITE4_INC@,$SQLITE4_INC,;t t
+s,@SQLITE4_A10N_C@,$SQLITE4_A10N_C,;t t
+s,@SQLITE4_A10N_FLAGS@,$SQLITE4_A10N_FLAGS,;t t
+s,@XML2_FLAGS@,$XML2_FLAGS,;t t
+s,@XML2_LIBS@,$XML2_LIBS,;t t
+s,@EXT_XPATH@,$EXT_XPATH,;t t
 s,@LIB_TARGETS@,$LIB_TARGETS,;t t
 s,@INST_TARGETS@,$INST_TARGETS,;t t
 s,@UNINST_TARGETS@,$UNINST_TARGETS,;t t
@@ -21936,6 +22024,8 @@ s,@DRVDIR@,$DRVDIR,;t t
 s,@DL_OPTS@,$DL_OPTS,;t t
 s,@DL_INITFINI@,$DL_INITFINI,;t t
 s,@SQLITE3_LIB@,$SQLITE3_LIB,;t t
+s,@SQLITE3_A10N_O@,$SQLITE3_A10N_O,;t t
+s,@SQLITE4_A10N_O@,$SQLITE4_A10N_O,;t t
 s,@SPEC_CHANGELOG_TS@,$SPEC_CHANGELOG_TS,;t t
 s,@DEB_CHANGELOG_TS@,$DEB_CHANGELOG_TS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
